"""empty message

Revision ID: 42f28ca50002
Revises: 9e4746cf9591
Create Date: 2021-12-07 15:01:09.584906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f28ca50002'
down_revision = '9e4746cf9591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'img_url')
    # ### end Alembic commands ###
