"""empty message

Revision ID: d4755ddeb11f
Revises: 42f28ca50002
Create Date: 2021-12-07 15:32:59.295349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4755ddeb11f'
down_revision = '42f28ca50002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'img_url')
    # ### end Alembic commands ###
